# -*- coding: utf-8 -*-
"""Long COVID Pred-Synthetic Data Generation.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vAYNF-dSAoUQbV2i3IDOVEYbBgHO4yFO

**The codes below are used to generate synthetic data based on the kenya and malawi datasets**
"""

from DataSynthesizer.DataDescriber import DataDescriber
from DataSynthesizer.DataGenerator import DataGenerator
from DataSynthesizer.ModelInspector import ModelInspector
from DataSynthesizer.lib.utils import read_json_file, display_bayesian_network

import pandas as pd
import numpy as np

"""## Kenya"""

kenya_data = pd.read_csv('C:/Users/HP/Desktop/FYP/Dataset/Kenya, Malawi, Long Covid-19 effects survey dataset/kenya-long-covid-effects.csv', na_values=['nan', ' ', 'NAN', 'NaN', 'na', 'NA', 'N/A'])

kenya_disrupt = kenya_data.loc[:, 'C3.1_1':'C3b.3_8']

selected_cols = ['age', 'gender','Symptoms', 'C6', 'occupation', 'C10', 'C7', 'C4','C4b','C4b_5', 
                 'C3b.1_1','C3b.2_1','C3b.3_1', 'C22', 'communicable_disease','non_communicable_disease',
                 'body_organ_disease','neurological_condition', 'respiratory_condition','other_disease',
                 'C3b.1_7','C3b.2_7', 'C3b.3_7', 'C3.1_1','C3.2_1','C3.3_1']
kenya_data = kenya_data[selected_cols]

kenya_data['med_history'] = (kenya_data.loc[:, 'communicable_disease':'other_disease'] == 'Yes').any(axis=1)
kenya_data.loc[kenya_data['med_history']==True, 'med_history'] = 'Yes'
kenya_data.loc[kenya_data['med_history']==False, 'med_history'] = 'No'

kenya_data['long_symptoms']= (kenya_data.loc[:, 'C4':'C4b'] == 'None of the above').all(axis=1)
kenya_data.loc[kenya_data['long_symptoms']==True, 'long_symptoms'] = 1
kenya_data.loc[kenya_data['long_symptoms']==False, 'long_symptoms'] = 0

kenya_data['how_anxious'] = kenya_data.loc[:, ['C3b.1_1','C3b.2_1','C3b.3_1']].mode(axis=1)[0]
kenya_data['stress_lvl'] = kenya_data.loc[:, ['C3b.1_7','C3b.2_7', 'C3b.3_7']].mode(axis=1)[0]
kenya_data['energy_lvl'] = kenya_data.loc[:, ['C3.1_1','C3.2_1','C3.3_1']].mode(axis=1)[0]
kenya_data['how_disrupted'] = kenya_disrupt.mode(axis=1)[0]
kenya_data.loc[kenya_data['C10']=='I did nothing', 'C10'] = 'None of these apply'

symp_worst_dict = {'Recurrent fever':'Fever', 'Persistent cough':'Cough', 'Chest pain':'Difficulty Breathing/Chest Pressure', 
                   'Shortness of breath':'Difficulty Breathing/Chest Pressure', 'Joint pain':'Muscle Pain/Body Aches',
                   'Muscle pain and needles':'Muscle Pain/Body Aches', 'Loss of smell':'Loss of Taste or Smell',
                   'Loss of taste':'Loss of Taste or Smell', 'Acid reflux':'Other, Specify', 'None of the above':'No symptoms experienced',
                   'Back ache':'Muscle Pain/Body Aches', 'Vomiting':'Nausea/Vomiting', 'Nerve pain/burning':'Seizure or Loss of Consciousness', 'Abdominal pain':'Other, Specify',
                   'Palpitations':'Other, Specify', 'Rash':'Other, Specify', 'Post exertion malaise':'Other, Specify', 'Tinnitus (buzzing in ears)':'Other, Specify'}
kenya_data['C6'] = kenya_data['C6'] .replace(symp_worst_dict)

kenya_data = kenya_data.drop(columns=['C4','C4b','C3b.1_1','C3b.2_1','C3b.3_1', 'C3b.1_7','C3b.2_7', 'C3b.3_7', 'C3.1_1','C3.2_1','C3.3_1','communicable_disease','non_communicable_disease',
                                      'body_organ_disease','neurological_condition','respiratory_condition','other_disease'])

cols_rename_dict = {'Symptoms':'symptoms', 'occupation':'employ_status', 'C4b_5':'lasting_cognitive', 
                    'C6':'symptom_worst', 'C10':'treat_prescriptions', 'C7':'treat_hospital', 'C22':'vaccine_received'}
kenya_data = kenya_data.rename(cols_rename_dict, axis=1)

disrupt_dict = {'Never':'No disruption', 'Rarely':'Very mild disruption', 'Sometimes':'Mild to moderate disruption', 
                'Always':'Moderate to severe disruption', 'Very often':'Extreme disruption'}
kenya_data['how_disrupted'] = kenya_data['how_disrupted'].map(disrupt_dict)

anxiety_dict = {'Never':'No anxiety', 'Rarely':'Very mild anxiety', 'Sometimes':'Mild to moderate anxiety', 
                'Always':'Severe to Extreme anxiety', 'Very often':'Extreme anxiety'}
kenya_data['how_anxious'] = kenya_data['how_anxious'].map(anxiety_dict)

stress_dict = {'Never':'No change', 'Rarely':'Worsened them moderately', 'Sometimes':'Worsened them moderately', 
                'Always':'Worsened them significantly', 'Very often':'Worsened them significantly'}
kenya_data['stress_lvl'] = kenya_data['stress_lvl'].map(stress_dict)

energy_dict = {'Never':'No change', 'Rarely':'Worsened my energy moderately', 'Sometimes':'Worsened my energy moderately', 
                'Always':'Worsened my energy moderately', 'Very often':'Worsened my energy moderately'}
kenya_data['energy_lvl'] = kenya_data['energy_lvl'].map(energy_dict)

kenya_data['onset_date'] = np.nan

kenya_data.shape

"""###Malawi"""

malawi_data = pd.read_csv('C:/Users/HP/Desktop/FYP/Dataset/Kenya, Malawi, Long Covid-19 effects survey dataset/malawi-long-covid.csv', na_values=['nan', ' ', 'NAN', 'NaN', 'na', 'NA', 'N/A'])

malawi_disrupt = malawi_data.loc[:, 'C3.1_1':'C3b.3_8']

selected_cols = ['age', 'gender','Symptoms', 'date', 'C6', 'occupation', 'C10', 'C7', 'C4','C4b','C4b_5', 
                 'C3b.1_1','C3b.2_1','C3b.3_1', 'C22', 'communicable_disease','non_communicable_disease',
                 'body_organ_disease','neurological_condition', 'respiratory_condition','other_disease',
                 'C3b.1_7','C3b.2_7', 'C3b.3_7', 'C3.1_1','C3.2_1','C3.3_1']
malawi_data = malawi_data[selected_cols]

malawi_data['med_history'] = (malawi_data.loc[:, 'communicable_disease':'other_disease'] == 'Yes').any(axis=1)
malawi_data.loc[malawi_data['med_history']==True, 'med_history'] = 'Yes'
malawi_data.loc[malawi_data['med_history']==False, 'med_history'] = 'No'

malawi_data['long_symptoms']= (malawi_data.loc[:, 'C4':'C4b'] == 'None of the above').all(axis=1)
malawi_data.loc[malawi_data['long_symptoms']==True, 'long_symptoms'] = 1
malawi_data.loc[malawi_data['long_symptoms']==False, 'long_symptoms'] = 0

malawi_data['how_anxious'] = malawi_data.loc[:, ['C3b.1_1','C3b.2_1','C3b.3_1']].mode(axis=1)[0]
malawi_data['stress_lvl'] = malawi_data.loc[:, ['C3b.1_7','C3b.2_7', 'C3b.3_7']].mode(axis=1)[0]
malawi_data['energy_lvl'] = malawi_data.loc[:, ['C3.1_1','C3.2_1','C3.3_1']].mode(axis=1)[0]
malawi_data['how_disrupted'] = malawi_disrupt.mode(axis=1)[0]
malawi_data.loc[malawi_data['C10']=='I did nothing', 'C10'] = 'None of these apply'

symp_worst_dict = {'Recurrent fever':'Fever', 'Persistent cough':'Cough', 'Chest pain':'Difficulty Breathing/Chest Pressure', 
                   'Shortness of breath':'Difficulty Breathing/Chest Pressure', 'Joint pain':'Muscle Pain/Body Aches',
                   'Muscle pain and needles':'Muscle Pain/Body Aches', 'Loss of smell':'Loss of Taste or Smell',
                   'Loss of taste':'Loss of Taste or Smell', 'Acid reflux':'Other, Specify', 'None of the above':'No symptoms experienced',
                   'Back ache':'Muscle Pain/Body Aches', 'Vomiting':'Nausea/Vomiting', 'Nerve pain/burning':'Seizure or Loss of Consciousness', 'Abdominal pain':'Other, Specify',
                   'Palpitations':'Other, Specify', 'Rash':'Other, Specify', 'Post exertion malaise':'Other, Specify', 'Tinnitus (buzzing in ears)':'Other, Specify'}
malawi_data['C6'] = malawi_data['C6'] .replace(symp_worst_dict)

malawi_data = malawi_data.drop(columns=['C4','C4b','C3b.1_1','C3b.2_1','C3b.3_1', 'C3b.1_7','C3b.2_7', 'C3b.3_7', 'C3.1_1','C3.2_1','C3.3_1','communicable_disease','non_communicable_disease',
                                      'body_organ_disease','neurological_condition','respiratory_condition','other_disease'])

cols_rename_dict = {'Symptoms':'symptoms', 'date':'onset_date', 'occupation':'employ_status', 'C4b_5':'lasting_cognitive', 
                    'C6':'symptom_worst', 'C10':'treat_prescriptions', 'C7':'treat_hospital', 'C22':'vaccine_received'}
malawi_data = malawi_data.rename(cols_rename_dict, axis=1)

disrupt_dict = {'Never':'No disruption', 'Rarely':'Very mild disruption', 'Sometimes':'Mild to moderate disruption', 
                'Always':'Moderate to severe disruption', 'Very often':'Extreme disruption'}
malawi_data['how_disrupted'] = malawi_data['how_disrupted'].map(disrupt_dict)

anxiety_dict = {'Never':'No anxiety', 'Rarely':'Very mild anxiety', 'Sometimes':'Mild to moderate anxiety', 
                'Always':'Severe to Extreme anxiety', 'Very often':'Extreme anxiety'}
malawi_data['how_anxious'] = malawi_data['how_anxious'].map(anxiety_dict)

stress_dict = {'Never':'No change', 'Rarely':'Worsened them moderately', 'Sometimes':'Worsened them moderately', 
                'Always':'Worsened them significantly', 'Very often':'Worsened them significantly'}
malawi_data['stress_lvl'] = malawi_data['stress_lvl'].map(stress_dict)

energy_dict = {'Never':'No change', 'Rarely':'Worsened my energy moderately', 'Sometimes':'Worsened my energy moderately', 
                'Always':'Worsened my energy moderately', 'Very often':'Worsened my energy moderately'}
malawi_data['energy_lvl'] = malawi_data['energy_lvl'].map(energy_dict)

malawi_data['onset_date'] = pd.to_datetime(malawi_data['onset_date'], format='%Y-%m-%d', errors='coerce')

"""## Combine"""

km_data = pd.concat([kenya_data, malawi_data])
km_data.shape
km_data['long_symptoms'].value_counts()

km_data.columns

km_file = km_data.to_csv("C:/Users/HP/Desktop/FYP/Dataset/Kenya, Malawi, Long Covid-19 effects survey dataset/km-long-covid.csv")

"""## SDG"""

# input dataset
input_data = "C:/Users/HP/Desktop/FYP/Dataset/Kenya, Malawi, Long Covid-19 effects survey dataset/km-long-covid.csv"
# location of two output files
mode = 'independent_attribute_mode'
description_file = f'C:/Users/HP/Desktop/FYP/Dataset/Kenya, Malawi, Long Covid-19 effects survey dataset/description2.json'
synthetic_data = f'C:/Users/HP/Desktop/FYP/Dataset/Kenya, Malawi, Long Covid-19 effects survey dataset/sythetic_data2.csv'

# An attribute is categorical if its domain size is less than this threshold.
# Here modify the threshold to adapt to the domain size of "education" (which is 14 in input dataset).
threshold_value = 20 

# specify categorical attributes
categorical_attributes = {'age': True, 'gender': True, 'symptoms': True, 'symptom_worst': True, 
                          'employ_status': True, 'treat_prescriptions': True, 'treat_hospital': True, 'lasting_cognitive': True,
                          'vaccine_received': True, 'med_history': True, 'long_symptoms': True, 'how_anxious':True,
                          'stress_lvl': True, 'energy_lvl': True, 'how_disrupted': True}
       

# Number of tuples generated in synthetic dataset.
num_tuples_to_generate = 500

describer = DataDescriber(category_threshold=threshold_value)
describer.describe_dataset_in_independent_attribute_mode(dataset_file=input_data,
                                                         attribute_to_is_categorical=categorical_attributes)
#attribute_to_is_candidate_key=candidate_keys
describer.save_dataset_description_to_file(description_file)

generator = DataGenerator()
generator.generate_dataset_in_independent_mode(num_tuples_to_generate, description_file)
generator.save_synthetic_data(synthetic_data)

syn_data = pd.read_csv('C:/Users/HP/Desktop/FYP/Dataset/Kenya, Malawi, Long Covid-19 effects survey dataset/sythetic_data2.csv')
print(syn_data['long_symptoms'].value_counts())